# -*- coding: utf-8 -*-
"""12191627_오영제_Project#2-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VLa8iDtpWbZZ3qCNuhRjYURQzgkM3SPR
"""

from google.colab import files
file_upload = files.upload()

import io
import pandas as pd

df = pd.read_csv(io.BytesIO(file_upload["2019_kbo_for_kaggle_v2.csv"]), encoding="cp949")
df = df.sort_values(by='year')

for year in range(2015, 2019):
  template = ['batter_name', '', 'year']

  options = ['H', 'avg', 'HR', 'OBP']
  for option in options:
    template[1] = option
    result = df[df['year']==year].nlargest(10, option)
    print(result[template])

dfSeason2018 = df[df["year"] == 2018]

result5 = dfSeason2018.sort_values(by='war', ascending = False).groupby('cp', sort = False)
print(result5[['batter_name', 'cp']].head(1))

elems = ['R', 'H', 'HR', 'RBI', 'SB', 'war', 'avg', 'OBP', 'SLG']
ans = ''
tempCorr = -1

for elem in elems:
  curCorr = df['salary'].corr(df[elem])
  if tempCorr < curCorr:
    ans = elem
    tempCorr = curCorr

print(f"\n연봉에 highest correlation을 가진 열 : {ans}입니다")